const icon = (paths) => `<svg viewBox="0 0 24 24" aria-hidden="true">${paths}</svg>`;

export const TOOLS = [
  {
    id: 'password',
    title: 'Password generator and strength checker',
    category: 'Security',
    summary: 'Create secure random passwords with length, character set, strength, and copy controls.',
    icon: icon('<rect x="4" y="10" width="16" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/><path d="M12 14v2"/>'),
  },
  {
    id: 'hash',
    title: 'Hash generator and checksum tool',
    category: 'Security',
    summary: 'Generate MD5 and SHA hashes for text or local files entirely in the browser.',
    keywords: 'checksum md5 sha-1 sha-256 sha-384 sha-512 file hash digest',
    icon: icon('<path d="M4 9V6a2 2 0 0 1 2-2h3"/><path d="M20 15v3a2 2 0 0 1-2 2h-3"/><path d="M9 20H6a2 2 0 0 1-2-2v-3"/><path d="M15 4h3a2 2 0 0 1 2 2v3"/><path d="M8 8h8v8H8z"/><path d="M11 11h2v2h-2z"/>'),
  },
  {
    id: 'case',
    title: 'Text case converter',
    category: 'Text',
    summary: 'Convert text to lowercase, uppercase, title case, camelCase, or snake_case with live previews.',
    icon: icon('<path d="M4 7h9"/><path d="M8.5 7v10"/><path d="M15 17l3-8 3 8"/><path d="M16 14h4"/>'),
  },
  {
    id: 'counter',
    title: 'Character and word counter',
    category: 'Text',
    summary: 'Count characters, words, and sentences as text changes.',
    icon: icon('<path d="M4 6h16"/><path d="M4 12h10"/><path d="M4 18h8"/><path d="M17 15l2 2 3-4"/>'),
  },
  {
    id: 'json',
    title: 'JSON formatter and validator',
    category: 'Data',
    summary: 'Validate, pretty-print, minify, and export JSON with optional recursive key sorting.',
    keywords: 'json formatter validator pretty print minify lint parse beautify',
    icon: icon('<path d="M9 4H7a2 2 0 0 0-2 2v3"/><path d="M9 20H7a2 2 0 0 1-2-2v-3"/><path d="M15 4h2a2 2 0 0 1 2 2v3"/><path d="M15 20h2a2 2 0 0 0 2-2v-3"/><path d="M10 9h4"/><path d="M10 15h4"/><path d="M12 9v6"/>'),
  },
  {
    id: 'encode',
    title: 'Base64 and URL encoder-decoder',
    category: 'Encoding',
    summary: 'Encode or decode UTF-8 text with Base64, URL-safe Base64, or percent-encoding.',
    keywords: 'base64 base64url url encode decode percent encoding utf-8',
    icon: icon('<path d="M4 8h10"/><path d="M4 16h10"/><path d="M14 12H4"/><path d="m16 7 4 5-4 5"/><path d="m10 5-2 14"/>'),
  },
  {
    id: 'qr',
    title: 'QR code generator',
    category: 'Share',
    summary: 'Generate a downloadable QR code from text or a URL instantly.',
    icon: icon('<rect x="4" y="4" width="6" height="6"/><rect x="14" y="4" width="6" height="6"/><rect x="4" y="14" width="6" height="6"/><path d="M14 14h2v2h-2z"/><path d="M18 14h2v6h-4v-2h2z"/>'),
  },
  {
    id: 'speed',
    title: 'Connection speed test',
    category: 'Network',
    summary: 'Measure ping, jitter, download, and upload speeds against your configured speed test server.',
    keywords: 'network speed test latency ping jitter bandwidth download upload',
    icon: icon('<path d="M12 19a7 7 0 1 0-7-7"/><path d="M12 12l4-4"/><path d="M4.6 17.4 3 19"/><path d="M20.9 19l-1.5-1.6"/>'),
  },
  {
    id: 'timezone',
    title: 'Timezone converter',
    category: 'Time',
    summary: 'Convert a date and time between common global timezones using browser Intl data.',
    icon: icon('<circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/><path d="M3 12h2"/><path d="M19 12h2"/>'),
  },
  {
    id: 'datetime',
    title: 'Date difference and timestamp converter',
    category: 'Time',
    summary: 'Parse dates or Unix timestamps, inspect UTC or local output, and compare exact elapsed time.',
    keywords: 'unix timestamp epoch date difference time between iso 8601 utc local',
    icon: icon('<rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4"/><path d="M16 3v4"/><path d="M4 10h16"/><path d="M8 14h3"/><path d="M13 14h3"/><path d="M8 17h8"/>'),
  },
  {
    id: 'timer',
    title: 'Countdown and stopwatch',
    category: 'Time',
    summary: 'Run a focused countdown or track elapsed time with quick lap capture.',
    icon: icon('<path d="M9 2h6"/><path d="M12 14l3-3"/><circle cx="12" cy="14" r="8"/><path d="M18 5l1.5 1.5"/>'),
  },
  {
    id: 'random',
    title: 'Random number generator',
    category: 'Numbers',
    summary: 'Generate secure random integers, including optional unique sets.',
    icon: icon('<path d="M4 7h4l8 10h4"/><path d="M18 7h2v2"/><path d="M4 17h4l2.2-2.8"/><path d="M15.8 9.8 18 7"/><path d="M18 17h2v-2"/>'),
  },
  {
    id: 'uuid',
    title: 'UUID generator',
    category: 'Developer',
    summary: 'Generate batches of RFC 4122 version 4 UUIDs with export-ready formatting controls.',
    keywords: 'uuid guid v4 identifier batch random id',
    icon: icon('<rect x="4" y="6" width="6" height="6" rx="1"/><rect x="14" y="6" width="6" height="6" rx="1"/><rect x="4" y="16" width="6" height="4" rx="1"/><path d="M14 16h6"/><path d="M17 12v8"/>'),
  },
  {
    id: 'converter',
    title: 'Unit converter',
    category: 'Measure',
    summary: 'Convert length, weight, temperature, and digital storage values instantly.',
    icon: icon('<path d="M4 7h16"/><path d="M4 17h16"/><path d="M7 7v10"/><path d="M12 7v4"/><path d="M17 7v10"/>'),
  },
];
